### ISSUE TITLE
Error with Infura - Might have reached daily requests limit

### ISSUE THREAD

**Issue by nunocgoncalves** [Pizza-Wallet-Development-team/pizza-wallet#2]
```shell
error Error: {
  "code": -32603,
  "message": "Non-200 status code: '429'",
  "data": {
    "jsonrpc": "2.0",
    "id": 594433710128151,
    "error": {
      "code": -32005,
      "message": "daily request count exceeded, request rate limited",
      "data": {
        "rate": {
          "allowed_rps": 1,
          "backoff_seconds": 30,
          "current_rps": 2.7333333333333334
        },
        "see": "https://infura.io/dashboard"
      }
    }
  },
  "stack": "Error: Non-200 status code: '429'\n    at s (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:2414544)\n    at Object.internal (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:2415255)\n    at U (https://pizza-wallet.vercel.app/static/js/0.1395a69b.chunk.js:2:14899)\n    at https://pizza-wallet.vercel.app/static/js/0.1395a69b.chunk.js:2:15819\n    at l (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:1470791)\n    at Generator._invoke (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:1470579)\n    at Generator.next (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:1471220)\n    at r (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:17162)\n    at s (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:17365)"
}
    at INetworkController.ts:117:13
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9) {
  "code": -32603,
  "message": "Non-200 status code: '429'",
  "data": {
    "jsonrpc": "2.0",
    "id": 594433710128151,
    "error": {
      "code": -32005,
      "message": "daily request count exceeded, request rate limited",
      "data": {
        "rate": {
          "allowed_rps": 1,
          "backoff_seconds": 30,
          "current_rps": 2.7333333333333334
        },
        "see": "https://infura.io/dashboard"
      }
    }
  },
  "stack": "Error: Non-200 status code: '429'\n    at s (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:2414544)\n    at Object.internal (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:2415255)\n    at U (https://pizza-wallet.vercel.app/static/js/0.1395a69b.chunk.js:2:14899)\n    at https://pizza-wallet.vercel.app/static/js/0.1395a69b.chunk.js:2:15819\n    at l (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:1470791)\n    at Generator._invoke (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:1470579)\n    at Generator.next (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:1471220)\n    at r (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:17162)\n    at s (https://pizza-wallet.vercel.app/static/js/6.c16ff95f.chunk.js:2:17365)"
}
```

**Comment by nunocgoncalves** [comment]
Not using custom RPCs on Infura anymore
