### ISSUE TITLE
"Could not connect via Web3Auth, error in connecting to provider"

### ISSUE THREAD

**Issue by nunocgoncalves** [Pizza-Wallet-Development-team/pizza-wallet#6]
Console Error Message:

```shell
Error while connecting to adapter: openlogin WalletLoginError: Failed to connect with walletFailed to login with openlogin
    at Function.value (index.ts:143:12)
    at Function.value (index.ts:147:12)
    at u.<anonymous> (openloginAdapter.ts:131:13)
    at l (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.throw (runtime.js:119:21)
    at r (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:29:9)
```

![image](https://user-images.githubusercontent.com/64640406/167458137-6fc62eb8-f935-4ff1-9366-3de86d2e9e75.png)

**Comment by nunocgoncalves** [comment]
Fixed! Changed web3auth Client ID
