### ISSUE TITLE
Transfer Component doesn´t load on the PR #58

### ISSUE THREAD

**Issue by nunocgoncalves** [Pizza-Wallet-Development-team/pizza-wallet#60]
**Describe the bug**
Transfer Component doesn´t load on the PR #58

**To Reproduce**
1. Go to [PR 58 Build](https://bafybeiar4g3kr4dpulodtxthyvros2xz3avtwrsgkgv4w6ufq2adkz2mca.on.fleek.co/#/transfer)
2. Page doesn't load
Screenshot:
![image](https://user-images.githubusercontent.com/64640406/192227312-d662ac89-f53c-4aca-b698-f04b1be262c8.png)
Console output:
```sh
TypeError: Cannot read properties of undefined (reading 'includes')
    at u (sendRestPayload.ts:29:12)
    at p (alchemyContext.ts:31:22)
    at m (index.ts?0e3e:173:5)
    at Qe (useWeb3.js:5:16)
    at oo (react-dom.production.min.js:157:137)
    at Jc (react-dom.production.min.js:267:460)
    at Ns (react-dom.production.min.js:250:347)
    at Ss (react-dom.production.min.js:250:278)
    at As (react-dom.production.min.js:250:138)
    at ys (react-dom.production.min.js:243:163)
```

**Expected behavior**
The page should load the following plus the newly developed feature.
![image](https://user-images.githubusercontent.com/64640406/192227723-5f817d90-7511-46c4-be7e-1e18593bf5f9.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave
 - Version: v1.43.93

**Comment by nunocgoncalves** [comment]
The bug was a result of a missing ENV (REACT_APP_PROVIDER_URL) in the CI/CD environment as pointed out by @gitChimp88. Fixed!
